default:
  true

MD013:
  code_blocks: false
  tables: false

# Honestly most of the lint rules are absurd, we disable these *at least*

# First line in a file should be a top-level heading
MD041: false
# Multiple top-level headings in the same document
MD025: false
# Inline HTML
MD033: false
# Multiple consecutive blank lines
MD012: false

# Blank line inside blockquote
# gives false positives on code blocks for literal consecutive blockquotes
MD028: false
