# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

tasks:
  - init: |
      # runs during prebuild
      (
        set -e

        # install `deno` for bootstrap into workspace dir
        # https://www.gitpod.io/docs/configure/projects/prebuilds#workspace-directory-only
        curl -fsSL https://deno.land/install.sh | DENO_INSTALL=.deno sh
      )
    command: |
      # runs during startup
      (
        set -e
        .deno/bin/deno task compile
        echo "./tea is hot"
      )
