name: CI·sync

on:
  pull_request:
    paths:
      - import-map.json
      - src/hooks/app.sync.ts
      - src/hooks/useSync.ts
      - .github/workflows/ci.sync.yml

concurrency:
  group: ${{ github.ref }}/sync
  cancel-in-progress: true

jobs:
  # in situations without `git` we had a softlock problem that we're testing for here
  test-sync-lock:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
          - runner: macos-latest
          - runner: ubuntu-latest
            container: debian:buster-slim
          - runner: ubuntu-latest
            container: archlinux:latest
    container: ${{ matrix.platform.container }}
    name: test sync-lock (${{ matrix.platform.container || matrix.platform.runner }})
    env:
      DENO_DIR: ${{ env.HOME }}/.cache/deno
    steps:
      # denoland/setup requires `unzip` to be installed
      # https://github.com/denoland/setup-deno/issues/41
      - name: ensure `unzip`
        run: |
          case "${{ matrix.platform.container }}" in
          debian:buster-slim)
            apt-get update && apt-get install unzip;;
          archlinux:latest)
            pacman -Sy --noconfirm unzip;;
          esac

      - uses: actions/checkout@v3

      # avoiding sporadic 500 errors from deno’s CDN
      - uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ runner.os }}-deno-get-platform-${{ hashFiles('deno.jsonc')}}

      - uses: denoland/setup-deno@v1

      - run: deno task --config $GITHUB_WORKSPACE/deno.jsonc compile
        working-directory: /usr/local/bin

      - run: tea -S +gnu.org/wget wget -L tea.xyz/white-paper/ | tea -S +charm.sh/glow glow -

      # run again to test this work in the “update” scenario
      - run: tea -S +gnu.org/wget wget -L tea.xyz/white-paper/ | tea -S +charm.sh/glow glow -
