on:
  release:
    types:
      - created
      - edited
permissions:
  actions: write
jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fischerscode/tagger@v0
        with:
          prefix: v
